### ISSUE TITLE
Problems with trivial generic wreath product

### ISSUE THREAD

**Issue by DominikBernhardt** [FriedrichRober/WreathProductElements#14]
```
wr := WreathProduct( SymmetricGroup(2), SymmetricGroup(2));
iso := IsomorphismToGenericWreathProduct( wr );
GeneratorsOfGroup(Image(iso, TrivialSubgroup(wr)));
```
gives an empty list and not the list containing the trivial wreath product element. This is a problem for algorithms that want to access the generators of a group.
This is somewhat urgent and should be fixed.

**Comment by FriedrichRober** [comment]
I looked a little bit into this problem and think this is a GAP related issue with the command `TrivialSubgroup`.

```
gap> grp := TrivialSubgroup(Group((1,2,3,4),(1,2)));
Group(())
gap> GeneratorsOfGroup(grp);
[  ]
gap> GeneratorsOfGroup(Group(()));
[ () ]
```

I will investigate further to see if I can fix this problem or at least make a pull request on the GAP repository.

**Comment by FriedrichRober** [comment]
As a quick workaround if you need to construct the trivial group, the following code works as intended:
```
gap> wr := WreathProduct( SymmetricGroup(2), SymmetricGroup(2));;
gap> iso := IsomorphismToGenericWreathProduct( wr );;
gap> grp := Group(One(Image(iso)));
<group with 1 generators>
gap> GeneratorsOfGroup(grp);
[ WreathProductElement((),();()) ]
```

**Comment by FriedrichRober** [comment]
Ok, it seems that this issue was discussed already on the GAP repo and it was decided that an empty list is acceptable.
So there really is nothing I can do about this.
